project_id = "hvzxsjoszgakugpstipe"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.telegram-bot]
verify_jwt = false

[functions.sync-load]
verify_jwt = false

[functions.sync-save]
verify_jwt = false