// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvzxsjoszgakugpstipe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2enhzam9zemdha3VncHN0aXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDYxNjUsImV4cCI6MjA2MzQyMjE2NX0.0sBBALeiGBLk_tvG6XnrNRQ3KAjicTtCzqSLPLUZYxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});